import Header from "../components/Header"
import styles from "./demos.module.css"




export default function Demons(){
    return <>
    <div>
        <Header></Header>
        <div style={{whiteSpace: 'pre-line'}} className={styles.demonList}>
        {`
            Abaddon
            Aamon
            Abigor
            Abezethibou
            Abraxas
            Adramelech
            Aeshma
            Agaliarept
            Agrat Bat Mahlat
            Aim
            Akuma
            Alloces
            Alocer
            Amdusias
            Amon
            Amy
            Andras
            Andrealphus
            Andromalius
            Apollyon
            Arachne
            Asag
            Asmodeus
            Astaroth
            Ashtaroth
            Astarte
            Aym
            Azazel
            Baal
            Baalberith
            Balam
            Barbatos
            Baphomet
            Barbas
            Bathin
            Beelzebub
            Belial
            Belphegor
            Berith
            Bifrons
            Botis
            Buer
            Caim
            Camio
            Carabia
            Cerberus
            Choronzon
            Clisthert
            Cimeries
            Crocell
            Dagon
            Dantalion
            Decarabia
            Demonax
            Eligos
            Eisheth
            Eurynome
            Furcas
            Furfur
            Gaap
            Gadreel
            Geryon
            Gorgon
            Gremory
            Halphas
            Haures
            Ipos
            Incubus
            Jezebeth
            Kobal
            Chronos
            Leraie
            Leviathan
            Lilith
            Lucifer
            Malphas
            Mammon
            Marchosias
            Marax
            Mastema
            Medusa
            Mephistopheles
            Merihim
            Moloch
            Morax
            Murmur
            Naberius
            Naamah
            Nybbas
            Orobas
            Ose
            Paimon
            Phenex
            Procel
            Purson
            Raum
            Ronove
            Sallos
            Saleos
            Samael
            Seere
            Shax
            Stolas
            Succubus
            Tartarus
            Valac
            Valefar
            Vapula
            Vassago
            Vepar
            Vine
            Vual
            Xaphan
            Zagan
            Zepar
            Abatu
            Abigar
            Ablamon
            Adiel
            Adonai
            Ahpuch
            Ahriman
            Aka Manah
            Alastor
            Alocer
            Amoniel
            Andrasiel
            Angra Mainyu
            Anzu
            Apollyon
            Armaros
            Asag
            Asmodeus
            Astarte
            Astaroth
            Azrael
            Baalberith
            Baalzebub
            Barbatos
            Baphomet
            Beherit
            Belial
            Belphegor
            Berith
            Buer
            Caim
            Choronzon
            Dagon
            Decarabia
            Eblis
            Eligos
            Focalor
            Foras
            Furcas
            Gaap
            Gamaliel
            Gorgon
            Ipos
            Chronos
            Leviathan
            Lilith
            Lucifuge
            Mammon
            Marax
            Mastema
            Mephistophiles
            Moloch
            Murmur
            Naberius
            Oriax
            Ose
            Paimon
            Phenex
            Purson
            Ronove
            Sallos
            Saleos
            Samael
            Seere
            Shax
            Stolas
            Valac
            Valefar
            Vapula
            Vassago
            Vepar
            Vine
            Vual
            Zagan
            Zepar
            `}
        </div>
    </div>
    </>
}